### ISSUE TITLE
PyLint-based plugin in CudaText cannot work on embedded Windows Python 3.12.9 x64

### ISSUE THREAD

**Issue by Alexey-T** [pylint-dev/pylint#10249]
I get this error in CudaText console panel (on the bottom, click the sidebar button):
```
Init: cuda_lint
ERROR: exception in pylint.check: cannot import name 'formatargspec' from 'inspect' (C:\CudaText\python312.zip\inspect.pyc)
```

I checked file inspect.pyc and I cannot find that symbol 'formatargspec'.

I tried to upgrage 'pylint' module to the last 3.3.4 version, did not help.
Homepage of plugin: https://github.com/cudatext-addons/cuda_lint_pylint (has old pylint version 2.x which also shown the same error).

To install PyLint based plugin in CudaText:

- 'plugins / addon manager / install'
- find in listbox item 'PyLint' and ENTER

**Comment by jacobtylerwalls** [comment]
This sounds like an issue with the plugin. pylint core doesn't import `formatargspec`
