### ISSUE TITLE
Crash ``Building error when trying to create ast representation of module`` with Python 3.8.12

### ISSUE THREAD

**Issue by yuto-yuto** [pylint-dev/pylint#9166]
Sharing the code is not an option. So I share only the following traceback.

### Command used

```shell
pylint a.py
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidBuildingError`` and with the following stacktrace:
    </summary>

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 976, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "/usr/local/lib/python3.8/site-packages/astroid/manager.py", line 151, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/local/lib/python3.8/site-packages/astroid/builder.py", line 140, in file_build
    return self._post_build(module, builder, encoding)
  File "/usr/local/lib/python3.8/site-packages/astroid/builder.py", line 164, in _post_build
    self.delayed_assattr(delayed)
  File "/usr/local/lib/python3.8/site-packages/astroid/builder.py", line 236, in delayed_assattr
    for inferred in node.expr.infer():
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 1090, in _infer_attribute
    for owner in node.expr.infer(context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/bases.py", line 179, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/bases.py", line 179, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 1756, in _infer
    for callee in self.func.infer(context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 1090, in _infer_attribute
    for owner in node.expr.infer(context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 1090, in _infer_attribute
    for owner in node.expr.infer(context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/bases.py", line 179, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/bases.py", line 179, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 1756, in _infer
    for callee in self.func.infer(context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 1090, in _infer_attribute
    for owner in node.expr.infer(context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/bases.py", line 179, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/node_classes.py", line 2870, in _infer
    stmts = module.getattr(name, ignore_locals=module is self.root())
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 353, in getattr
    result = [self.import_module(name, relative_only=True)]
  File "/usr/local/lib/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 453, in import_module
    return AstroidManager().ast_from_module_name(
  File "/usr/local/lib/python3.8/site-packages/astroid/manager.py", line 259, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/usr/local/lib/python3.8/site-packages/astroid/manager.py", line 151, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/local/lib/python3.8/site-packages/astroid/builder.py", line 140, in file_build
    return self._post_build(module, builder, encoding)
  File "/usr/local/lib/python3.8/site-packages/astroid/builder.py", line 168, in _post_build
    module = self._manager.visit_transforms(module)
  File "/usr/local/lib/python3.8/site-packages/astroid/manager.py", line 114, in visit_transforms
    return self._transform.visit(node)
  File "/usr/local/lib/python3.8/site-packages/astroid/transforms.py", line 151, in visit
    return self._visit(node)
  File "/usr/local/lib/python3.8/site-packages/astroid/transforms.py", line 84, in _visit
    return self._transform(node)
  File "/usr/local/lib/python3.8/site-packages/astroid/transforms.py", line 66, in _transform
    ret = transform_func(node)
  File "/usr/local/lib/python3.8/site-packages/pylint_protobuf/transform.py", line 578, in transform_module
    for local_name, node in transform_descriptor_to_class(cls):
  File "/usr/local/lib/python3.8/site-packages/pylint_protobuf/transform.py", line 528, in transform_descriptor_to_class
    return transform_enum(desc, desc_registry)
  File "/usr/local/lib/python3.8/site-packages/pylint_protobuf/transform.py", line 328, in transform_enum
    simple_desc = descriptor_registry[cls_def.doc.split('=')[-1]]  # FIXME: guard?
AttributeError: 'ClassDef' object has no attribute 'doc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 716, in _get_asts
    ast_per_fileitem[fileitem] = self.get_ast(
  File "/usr/local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 998, in get_ast
    raise astroid.AstroidBuildingError(
astroid.exceptions.AstroidBuildingError: Building error when trying to create ast representation of module 'agent.data_api'

```

</details>

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.0.1
astroid 3.0.1
Python 3.8.12 (default, Jul  3 2023, 11:16:36) 
[GCC 10.2.1 20210110]
```

### OS / Environment

linux (Linux)

**Comment by yuto-yuto** [comment]
It works with pylint 2.17.7.
It crashed with pylint 3.0.0b0, 3.0.0, and 3.0.1

**Comment by DanielNoord** [comment]
This is an issue in `pylint_protobuf` and should be raised against them. The `doc` attribute was deprecated in `2.x` and removed in `3.x`.
