### PR TITLE
Fix crash in comparison-with-callable on a proxied lambda

### LINKED ISSUE #11175: Crash (astroid-error) in comparison-with-callable when comparing a lambda assigned as a class attribute
### Bug description

`comparison-with-callable` crashes with an `astroid-error` (F0002) when one side of a comparison infers to a **lambda that was assigned as a class attribute** and is accessed through an instance (`self.attr` / `Instance().attr`), i.e. astroid infers it as a `BoundMethod` proxying a `Lambda`:

```python
class C:
    lam = lambda self: 1

    def check(self):
        return self.lam == 1   # crash
```

### Command used

```shell
pylint --disable=all --enable=comparison-with-callable t.py
```

### Pylint output

```
Exception on node <Compare l.5 ...> in file 't.py'
Traceback (most recent call last):
  File ".../pylint/checkers/base/comparison_checker.py", line 287, in _check_callable_comparison
    and "typing._SpecialForm" not in inferred.decoratornames()
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File ".../astroid/bases.py", line 146, in __getattr__
    return getattr(self._proxied, name)
AttributeError: 'Lambda' object has no attribute 'decoratornames'

t.py:1:0: F0002: ... astroid-error ...
```

### Root cause

In `_check_callable_comparison` (`pylint/checkers/base/comparison_checker.py`):

```python
bare_callables = (nodes.FunctionDef, astroid.BoundMethod)
...
if (
    isinstance(inferred, bare_callables)
    and "typing._SpecialForm" not in inferred.decoratornames()   # <-- here
    and not any(isinstance(x, nodes.Raise) for x in inferred.body)
):
```

For `self.lam`, `safe_infer` returns a `BoundMethod` whose `_proxied` is a `Lambda`. It passes `isinstance(inferred, astroid.BoundMethod)`, but `decoratornames()` is defined on `FunctionDef`, **not** on `Lambda` (`hasattr(nodes.Lambda, "decoratornames")` is `False`), so the proxied attribute lookup raises `AttributeError`.

This is exactly the proxy pitfall called out in the repo's own `AGENTS.md` ("a `BoundMethod` can wrap a `Lambda`, which has no `.decorators`"). The `decoratornames()`/`.body` check was introduced in #11055.

### Two things a fix should be careful about

1. **A naive guard on `decoratornames()` alone still crashes on the next line.** `inferred.body` for a `Lambda` is a *single expression node*, not a list (`isinstance(nodes.Lambda(...).body, list)` is `False`, vs. `True` for `FunctionDef`), so `for x in inferred.body` would then raise `TypeError: '...' object is not iterable`.
2. **Bare lambdas are currently a false negative.** `f = lambda: 1; f == 1` emits nothing, because a `Lambda` is not an instance of `nodes.FunctionDef` (in this astroid, `issubclass(nodes.FunctionDef, nodes.Lambda)` is `False`). If `comparison-with-callable` is meant to cover lambdas, that's a related gap worth deciding on in the same change.

Because (2) is a behaviour decision (should comparing a bare/bound lambda to a non-callable be flagged, or just not crash?), I'm raising this as an issue first rather than sending a PR straight away. Happy to submit the fix once you confirm the intended behaviour — I have a patch and functional-test cases drafted.

### Pylint version

```shell
pylint 4.1.0-dev0
astroid 4.2.0b4
Python 3.12.3
```

### PR DESCRIPTION
**Pull request by Sanjays2402**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

A lambda assigned as a class attribute and read through an instance (`self.lam`) infers to a `BoundMethod` whose `_proxied` node is a `Lambda`. That passes `isinstance(inferred, bare_callables)`, but `Lambda` has no `decoratornames()`, so the proxy lookup raised `AttributeError` and aborted the whole module walk with `F0002` (astroid-error). Guarding only that call is not enough: `Lambda.body` is a single expression rather than a list, so the following `for x in inferred.body` would raise `TypeError` next.

Lambdas are not reported by `comparison-with-callable` today, so they are now skipped rather than crashing.

Closes #11175

### CODE REVIEW

**Review by DanielNoord — COMMENTED** [review]
Please don't use `hasattr` or `getattr`.

**Comment by Sanjays2402** [comment]
Good call — dropped the `hasattr`. Bound and unbound methods proxy the function they were built from, so I unwrap `_proxied` and then just check `isinstance(inferred, nodes.FunctionDef)`. A lambda assigned as a class attribute stays a `Lambda`, which is what the crash was about. `pytest tests/test_functional.py -k comparison_with_callable` is 2 passed. Pushed 356b877.

**Review by DanielNoord — DISMISSED** [review]
Can you add a Changelog entry (and ensure you do so in future PRs)?

**Comment by Sanjays2402** [comment]
Added `doc/whatsnew/fragments/11175.bugfix`, will do that up front in future PRs.

While I was in there I looked at the primer result on the last commit — it flagged a new `comparison-with-callable` on pytest's `hasinit()`, `init != object.__init__`. That was mine: `object.__init__` infers to a bare `UnboundMethod`, and unwrapping `UnboundMethod` turned it into a `FunctionDef`, so it counted as a bare callable. A lambda class attribute infers to a `BoundMethod` whose `_proxied` is the `Lambda`, so only the `BoundMethod` unwrap is needed; a plain method is a `BoundMethod` proxying an `UnboundMethod` proxying the `FunctionDef`, so that one unwraps twice. Reproduced the pytest snippet locally: it warns before the change, clean after.

Also added a functional case for the unbound-method comparison so this cannot regress silently. `pytest tests/test_functional.py -k comparison_with_callable` is 2 passed. Pushed 0af07f2.

**Comment by Pierre-Sassoulas** [comment]
Can you fix the check job please ?

**Comment by Sanjays2402** [comment]
Fixed in e33d04b. The check job was failing on `useless-suppression`, not on a real message:

```
pylint/checkers/base/comparison_checker.py:289:0: I0021: Useless suppression of 'protected-access'
pylint/checkers/base/comparison_checker.py:291:0: I0021: Useless suppression of 'protected-access'
```

`_proxied` on `BoundMethod`/`UnboundMethod` is not flagged by `protected-access` (the checker exempts attribute access on inferred non-instance nodes here), so the two `# pylint: disable=protected-access` comments I added were dead. Dropped both.

Verified with the same invocation CI uses: `pylint pylint/checkers/base/comparison_checker.py --enable=useless-suppression` reports the two I0021 lines before the change and rates 10.00/10 after. `tests/test_functional.py -k comparison_with_callable` still passes (2 passed).

**Review by DanielNoord — APPROVED** [review]
